apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/b-zago/box
        revision: HEAD
        directories:
          - path: k3s/workloads/*/overlays/*
  template:
    metadata:
      name: "{{index .path.segments 2}}-{{.path.basename}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/b-zago/box
        targetRevision: HEAD
        path: "{{.path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry: #so it won't hang in outofsync state when something turns out to be broken
          refresh: true
          limit: 5
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 3m
