[pve-servers]
pve ansible_host=18.195.164.196 ansible_user=admin

[server]
k3s-server ansible_host=10.11.0.10

[agents]
k3s-agent-1 ansible_host=10.11.0.11
k3s-agent-2 ansible_host=10.11.0.12

[k3s:children]
server
agents

[k3s:vars]
ansible_user=op
k3s_version=v1.36.3+k3s1

[server:vars]
s3_bucket=b-zago-resources
s3_key=oidc/staging
s3_region=eu-central-1
