apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rikami-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/b-zago/charts
    chart: rikami
    targetRevision: 1.0.2
  destination:
    server: https://kubernetes.default.svc
    namespace: rikami-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
