env: staging

argocd_username: box
argocd_ip: 10.10.10.211
traefik_ip: 10.10.10.210
internal_ip: 10.10.10.212
metallb_pool: 10.10.10.210-10.10.10.219

domain: staging.zagoapps.com

argocd_password: "{{ vault_argocd_password }}"
ca_bucket: "{{ vault_ca_bucket }}"
ca_cert_path: "{{ vault_ca_cert_path }}"

s3_bucket: "{{ vault_s3_bucket }}"
s3_key: "{{ vault_s3_key }}"
s3_region: "{{ vault_s3_region }}"

force_ca_config: false

eso_role: metal_staging_role
pg_role: metal_staging_pgsql_role
iam_roles:
  metal_staging_role:
    sub: "system:serviceaccount:external-secrets:external-secrets"
    ssm_paths:
      - "/clusters/config"
      - "/clusters/staging/*"
      - "/clusters/pgsql/staging/*"
  metal_staging_pgsql_role:
    sub: "system:serviceaccount:postgresql-admin:postgresql-admin"
    ssm_paths:
      - "/clusters/pgsql/*"
