apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
  namespace: external-secrets
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-token
  namespace: prod
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  data:
    - secretKey: ghcr-token
      remoteRef:
        key: /clusters/config
        property: data.ghcr-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cf-token
  namespace: cert-manager
spec:
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  data:
    - secretKey: cf-token
      remoteRef:
        key: /clusters/config
        property: data.cf-token
