apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-ssm
  namespace: external-secrets
spec:
  refreshInterval: 1h
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-creds
  namespace: staging
spec:
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  refreshInterval: 0s
  target:
    name: ghcr-creds
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "b-zago",
                "password": "{{ .token }}",
                "auth": "{{ printf "%s:%s" "b-zago" .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: token
      remoteRef:
        key: /clusters/config
        property: data.ghcr-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cf-token
  namespace: cert-manager
spec:
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  refreshInterval: 0s
  data:
    - secretKey: cf-token
      remoteRef:
        key: /clusters/config
        property: data.cf-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  refreshInterval: 0s
  target:
    name: argocd-server-tls
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: /clusters/staging/ca/argocd
        property: cert
    - secretKey: tls.key
      remoteRef:
        key: /clusters/staging/ca/argocd
        property: key
