[server]
k3s-server ansible_host=10.10.10.11

[agents]
k3s-agent-1 ansible_host=10.10.10.12
k3s-agent-2 ansible_host=10.10.10.13

[k3s:children]
server
agents

[k3s:vars]
ansible_user=op
k3s_version=v1.36.3+k3s1

[server:vars]
s3_bucket=b-zago-resources
s3_key=oidc/staging
s3_region=eu-central-1
