# The list of databases. One per line.
# After adding to the list run script put-pgsql-db-bootstrap-job.sh
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-bootstrap
  namespace: postgresql-admin
data:
  databases: |
    simple-api
