apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  refreshInterval: 0s
  target:
    name: argocd-server-tls
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: /clusters/dev/ca/argocd
        property: cert
    - secretKey: tls.key
      remoteRef:
        key: /clusters/dev/ca/argocd
        property: key
