apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-server-tls
  namespace: argocd
spec:
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  refreshInterval: 0s
  target:
    name: argocd-server-tls
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: /clusters/${ENV}/ca/argocd
        property: cert
    - secretKey: tls.key
      remoteRef:
        key: /clusters/${ENV}/ca/argocd
        property: key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-creds
  namespace: ${ENV}
spec:
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  refreshPolicy: CreatedOnce
  refreshInterval: 0s
  target:
    name: ghcr-creds
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "b-zago",
                "password": "{{ .token }}",
                "auth": "{{ printf "%s:%s" "b-zago" .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: token
      remoteRef:
        key: /clusters/config
        property: data.ghcr-token
