apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ${ENV}-gateway
  namespace: ${ENV}
spec:
  listeners:
    - name: websecure
      hostname: "*.${DOMAIN}"
    - name: websecure-apex
      hostname: "${DOMAIN}"
