apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/config/
  - gateway.yaml
  - eso.yaml
  - databases.yaml

patches:
  - path: argocd-install-app.yaml
  - path: metallb.yaml
  - path: cert-manager.yaml
  - path: pgsql-bootstrap-cm.yaml
