pve_force: false
pve_suite: trixie
pve_component: pve-no-subscription
pve_keyring: /usr/share/keyrings/proxmox-archive-keyring.gpg
pve_keyring_url: https://enterprise.proxmox.com/debian/proxmox-archive-keyring-trixie.gpg
pve_keyring_sha256: "136673be77aba35dcce385b28737689ad64fd785a797e57897589aed08db6e45" # fill in, then commit — this one's meant to be public

pve_packages:
  - proxmox-ve
  - postfix
  - open-iscsi
  - chrony
